- hosts: frontend
  remote_user: ubuntu
  become: true
  gather_facts: yes


  vars_files:
    - variables.yml


  post_tasks:
    - include_tasks: ansible_event.yml
      vars:
        application: deploy_frontend


  tasks:

    # Check that we can reach services on the backend instance
    - name: Check all port numbers are accessible from current host
      wait_for:
        host: "backend.{{ domain }}"
        port: "{{ item }}"
        state: started
        delay: 0
        timeout: 3
      with_items:
        - 3306
    # SilverStripe
    - name: Check if SilverStripe is installed
      stat: path="{{ silverstripe_directory }}"
      register: silverstripe_dir

    - name: Create SilverStripe and install it with all dependencies
      composer:
        command: create-project
        arguments: silverstripe/installer ./silverstripe ^4
        working_dir: /var/www/html
        prefer_dist: yes
      when: not silverstripe_dir.stat.exists

    - name: Fix the permissions for SilverStripe
      file:
        path: "{{ silverstripe_directory }}"
        owner: www-data
        group: www-data
        mode: 0755
        state: directory
        recurse: yes

    - name: Set up SilverStripe
      template: src=templates/env dest="{{ silverstripe_directory }}.env"

    - name: Deploy some custom code
      copy:
        src: files/mysite/
        dest: "{{ silverstripe_directory }}mysite/"
        owner: www-data
        group: www-data
        mode: 0755

    - name: Configure my site through a template
      template: src=templates/mysite.yml dest="{{ silverstripe_directory }}mysite/_config/mysite.yml"
