filebeat.prospectors:

# Collect stdin
- type: stdin

# Collect a JSON file
- type: log
  paths:
    - /var/log/apps/*.json
  fields_under_root: true
  fields:
    application: php
  json.message_key: log


filebeat.modules:
- module: auditd
- module: nginx
- module: osquery
- module: system


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_password }}"
  dashboards.enabled: true
