filebeat.prospectors:

{% if inventory_hostname_short == 'frontend' %}
# Collect a standard log
- type: log
  paths:
    - /var/www/html/silverstripe/silverstripe.log
  fields_under_root: true
  fields:
    application: silverstripe

# Collect a JSON file
- type: log
  paths:
    - /var/www/html/silverstripe/silverstripe.json
  fields_under_root: true
  fields:
    application: silverstripe
  json.message_key: log
{% endif %}


filebeat.modules:
- module: auditd
- module: nginx
- module: osquery
- module: system
{% if inventory_hostname_short == 'backend' %}
- module: mysql
{% endif %}


name: "{{ inventory_hostname }}"
tags: ["{{ env }}", "lightsail"]


processors:
- add_cloud_metadata: ~
- add_host_metadata: ~


xpack.monitoring.enabled: true


output.elasticsearch:
  hosts: ["{{ elasticsearch_host }}"]
  username: "{{ elasticsearch_user }}"
  password: "{{ elasticsearch_password }}"


setup:
  kibana:
    host: "{{ kibana_host }}"
    username: "{{ elasticsearch_user }}"
    password: "{{ elasticsearch_password }}"
  dashboards.enabled: true
