SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      LogFileHandler: [ pushHandler, [ %$LogFileHandler ] ]
      JsonFileHandler: [ pushHandler, [ %$JsonFileHandler ] ]

  LogFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "./silverstripe.log"
      - "notice"

  JsonFileHandler:
    class: Monolog\Handler\StreamHandler
    constructor:
      - "./silverstripe.json"
      - "notice"
    properties:
      Formatter: %$Monolog\Formatter\JsonFormatter
